name: Functional Test
# This workflow is triggered on pushes to the repository.
on: [pull_request]

jobs:
  functional:
    name: Functional Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Functional Tests
        run: |
         ./func_tests.sh
